// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// principalFunction
Rcpp::List principalFunction(arma::mat& M, int& MinCoreSize);
RcppExport SEXP _OneNet_principalFunction(SEXP MSEXP, SEXP MinCoreSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< int& >::type MinCoreSize(MinCoreSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(principalFunction(M, MinCoreSize));
    return rcpp_result_gen;
END_RCPP
}
// hugeglasso_sub
Eigen::MatrixXd hugeglasso_sub(Eigen::MatrixXd& S, Eigen::MatrixXd& W, Eigen::MatrixXd& T, int d, double ilambda, int& df, bool scr);
RcppExport SEXP _OneNet_hugeglasso_sub(SEXP SSEXP, SEXP WSEXP, SEXP TSEXP, SEXP dSEXP, SEXP ilambdaSEXP, SEXP dfSEXP, SEXP scrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type S(SSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< int& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< bool >::type scr(scrSEXP);
    rcpp_result_gen = Rcpp::wrap(hugeglasso_sub(S, W, T, d, ilambda, df, scr));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_CompactGraph();

static const R_CallMethodDef CallEntries[] = {
    {"_OneNet_principalFunction", (DL_FUNC) &_OneNet_principalFunction, 2},
    {"_OneNet_hugeglasso_sub", (DL_FUNC) &_OneNet_hugeglasso_sub, 7},
    {"_rcpp_module_boot_CompactGraph", (DL_FUNC) &_rcpp_module_boot_CompactGraph, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_OneNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
