# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

principalFunction <- function(M, MinCoreSize) {
    .Call('_OneNet_principalFunction', PACKAGE = 'OneNet', M, MinCoreSize)
}

hugeglasso_sub <- function(S, W, T, d, ilambda, df, scr) {
    .Call('_OneNet_hugeglasso_sub', PACKAGE = 'OneNet', S, W, T, d, ilambda, df, scr)
}

